const orderData =  {
  Momo: {
    quantity: 4,
    unitPrice: 100,
  },
  Pizza: {
    quantity: 5,
    unitPrice: 200,
  },
  Chowmein: {
    quantity: 10,
    unitPrice: 300,
  },
  ChopSuey: {
    quantity: 10,
    unitPrice: 300,
  },
  MilkCoffee: {
    quantity: 10,
    unitPrice: 300,
  },
  BlackTea: {
    quantity: 10,
    unitPrice: 300,
  },
  CheesePizza: {
    quantity: 10,
    unitPrice: 300,
  },
  Coke: {
    quantity: 10,
    unitPrice: 300,
  },
  Lemonade: {
    quantity: 10,
    unitPrice: 300,
  },
};

const tablesData = {
  Table1: {
    id: 12,
    isBusy: true,
    totalOrders: 20,
    fullFilledOrders: 12,
    waitTimeSinceLastOrder: '3 minutes',
    aboutTheCustomer: 'Couples',
    tableBusyPeriod: '2 HOURS 40 MINUTES',
     //number of hours table is busy since the customer came in
  },
  Table2: {
    id: 2,
    isBusy: false,
    totalOrders: 4,
    fullFilledOrders: 2,
    waitTimeSinceLastOrder: '0 minute',
    aboutTheCustomer: 'FAMILIY',
    tableBusyPeriod: '1 HOURS 4 MINUTES',
    orderData,
  },
  Table3: {
    id: 3,
    isBusy: false,
    totalOrders: 3,
    fullFilledOrders: 2,
    waitTimeSinceLastOrder: '1 minute',
    aboutTheCustomer: 'REGULAR',
    tableBusyPeriod: '2 HOURS 30 MINUTES',
    orderData,
  },
  Table4: {
    id: 4,
    isBusy: true,
    totalOrders: 10,
    fullFilledOrders: 0,
    waitTimeSinceLastOrder: '20 minutes',
    aboutTheCustomer: 'FRIENDS',
    tableBusyPeriod: '2 HOURS 44 MINUTES',
    orderData,
  },
  Table5: {
    id: 5,
    isBusy: true,
    totalOrders: 10,
    fullFilledOrders: 0,
    waitTimeSinceLastOrder: '20 minutes',
    aboutTheCustomer: 'Family',
    tableBusyPeriod: '2 HOURS 2 MINUTES',

  },
  Table6: {
    id: 5,
    isBusy: true,
    totalOrders: 10,
    fullFilledOrders: 0,
    waitTimeSinceLastOrder: '20 minutes',
    aboutTheCustomer: 'SINGLE',
    tableBusyPeriod: '0 HOURS 3 MINUTES',
    orderData,
  },
  Table7: {
    id: 7,
    isBusy: true,
    totalOrders: 10,
    fullFilledOrders: 0,
    waitTimeSinceLastOrder: '20 minutes',
    aboutTheCustomer: 'Family',
    tableBusyPeriod: '2 hours',
    orderData,
  },
  Table8: {
    id: 8,
    isBusy: true,
    totalOrders: 10,
    fullFilledOrders: 0,
    waitTimeSinceLastOrder: '20 minutes',
    aboutTheCustomer: 'Family',
    tableBusyPeriod: '2 hours',
    orderData,
  },
  Table11: {
    id: 12,
    isBusy: true,
    totalOrders: 20,
    fullFilledOrders: 12,
    waitTimeSinceLastOrder: '3 minutes',
    aboutTheCustomer: 'Couples',
    tableBusyPeriod: '2 HOURS 40 MINUTES',
    orderData, //number of hours table is busy since the customer came in
  },
  Table21: {
    id: 2,
    isBusy: false,
    totalOrders: 4,
    fullFilledOrders: 2,
    waitTimeSinceLastOrder: '0 minute',
    aboutTheCustomer: 'FAMILIY',
    tableBusyPeriod: '1 HOURS 4 MINUTES',
    orderData,
  },
  Table31: {
    id: 3,
    isBusy: false,
    totalOrders: 3,
    fullFilledOrders: 2,
    waitTimeSinceLastOrder: '1 minute',
    aboutTheCustomer: 'REGULAR ',
    tableBusyPeriod: '2 HOURS 30 MINUTES',
    orderData,
  },
  Table41: {
    id: 4,
    isBusy: true,
    totalOrders: 10,
    fullFilledOrders: 0,
    waitTimeSinceLastOrder: '20 minutes',
    aboutTheCustomer: 'FRIENDS',
    tableBusyPeriod: '2 HOURS 44 MINUTES',
    orderData,
  },
  Table51: {
    id: 5,
    isBusy: true,
    totalOrders: 10,
    fullFilledOrders: 0,
    waitTimeSinceLastOrder: '20 minutes',
    aboutTheCustomer: 'Family',
    tableBusyPeriod: '2 HOURS 2 MINUTES',
    orderData,
  },
  Table61: {
    id: 5,
    isBusy: true,
    totalOrders: 10,
    fullFilledOrders: 0,
    waitTimeSinceLastOrder: '20 minutes',
    aboutTheCustomer: 'SINGLE',
    tableBusyPeriod: '0 HOURS 3 MINUTES',
    orderData,
  },
  Table71: {
    id: 7,
    isBusy: true,
    totalOrders: 10,
    fullFilledOrders: 0,
    waitTimeSinceLastOrder: '20 minutes',
    aboutTheCustomer: 'Family',
    tableBusyPeriod: '2 hours',
    orderData,
  },
  Table81: {
    id: 8,
    isBusy: true,
    totalOrders: 10,
    fullFilledOrders: 0,
    waitTimeSinceLastOrder: '20 minutes',
    aboutTheCustomer: 'Family',
    tableBusyPeriod: '2 hours',
    orderData,
  },
  Table13: {
    id: 12,
    isBusy: true,
    totalOrders: 20,
    fullFilledOrders: 12,
    waitTimeSinceLastOrder: '3 minutes',
    aboutTheCustomer: 'Couples',
    tableBusyPeriod: '2 HOURS 40 MINUTES',
    orderData, //number of hours table is busy since the customer came in
  },
  Table34: {
    id: 2,
    isBusy: false,
    totalOrders: 4,
    fullFilledOrders: 2,
    waitTimeSinceLastOrder: '0 minute',
    aboutTheCustomer: 'FAMILIY',
    tableBusyPeriod: '1 HOURS 4 MINUTES',
    orderData,
  },
  Table35: {
    id: 3,
    isBusy: false,
    totalOrders: 3,
    fullFilledOrders: 2,
    waitTimeSinceLastOrder: '1 minute',
    aboutTheCustomer: 'REGULAR',
    tableBusyPeriod: '2 HOURS 30 MINUTES',
    orderData,
  },
  Table46: {
    id: 4,
    isBusy: true,
    totalOrders: 10,
    fullFilledOrders: 0,
    waitTimeSinceLastOrder: '20 minutes',
    aboutTheCustomer: 'FRIENDS',
    tableBusyPeriod: '2 HOURS 44 MINUTES',
    orderData,
  },
  Table57: {
    id: 5,
    isBusy: true,
    totalOrders: 10,
    fullFilledOrders: 0,
    waitTimeSinceLastOrder: '20 minutes',
    aboutTheCustomer: 'GATHERING',
    tableBusyPeriod: '2 HOURS 2 MINUTES',
    orderData,
  },
  Table68: {
    id: 5,
    isBusy: true,
    totalOrders: 10,
    fullFilledOrders: 0,
    waitTimeSinceLastOrder: '20 minutes',
    aboutTheCustomer: 'SINGLE',
    tableBusyPeriod: '0 HOURS 3 MINUTES',
    orderData,
  },
  Table79: {
    id: 7,
    isBusy: true,
    totalOrders: 10,
    fullFilledOrders: 0,
    waitTimeSinceLastOrder: '20 minutes',
    aboutTheCustomer: 'Family',
    tableBusyPeriod: '2 hours',
    orderData,
  },
  Table80: {
    id: 8,
    isBusy: true,
    totalOrders: 10,
    fullFilledOrders: 0,
    waitTimeSinceLastOrder: '20 minutes',
    aboutTheCustomer: 'Family',
    tableBusyPeriod: '2 hours',
    orderData,
  },
  
};

export default tablesData;
